name: SonarQube Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: self-hosted

    # ✅ Esto habilita Environment Secrets
    environment: sonarqube

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Cache SonarScanner packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: |
          rm -rf "$HOME/sonar-scanner-8.0.1.6346-linux-x64"
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-8.0.1.6346-linux-x64.zip
          unzip -o -q sonar-scanner-cli-8.0.1.6346-linux-x64.zip -d "$HOME"
          echo "$HOME/sonar-scanner-8.0.1.6346-linux-x64/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        env:
          # ✅ Recomendado: muévelo a Environment Secret o Variable
          # Si lo pones como secret de environment: SONAR_HOST_URL
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=mi_proyecto_seguro \
            -Dsonar.sources=. \
            -Dsonar.host.url="$SONAR_HOST_URL" \
            -Dsonar.token="$SONAR_TOKEN" \
            -Dsonar.python.version=3.10
